---
# tasks file for ansible_nginx
- name: add repository
  yum_repository:
    name: nginx
    description: NGINX Repository
    file: nginx-repo
    baseurl: http://nginx.org/packages/mainline/rhel/{{ ansible_distribution_major_version }}/$basearch/
    gpgcheck: no
    enabled: yes

- name: install nginx and dependencies
  yum:
    name:
      - nginx-1.9.0
    state: present
  notify: start nginx {{ ansible_distribution }} {{ ansible_distribution_major_version }}

- name: copy webpage
  template:
    src: templates/index.html.j2
    dest: /etc/nginx/html/index.html
    mode: '0644'
  notify: reload nginx {{ ansible_distribution }} {{ ansible_distribution_major_version }}

